apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: sync-gateway
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: sync-gateway
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway
          # args:
          command:
            - sync_gateway
            - https://gist.githubusercontent.com/bcbroussard/7f5174f424e22ce733da/raw/cfa22dc57e3b61bc7f3976faff67012cb0d9daf7/sync-gateway.config
            # https://raw.githubusercontent.com/couchbase/kubernetes/master/config/sync-gateway.config
          ports:
            - containerPort: 4984
            - containerPort: 4985